import{a as g,S as h,i as b}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const w="44900645-90bb6bb627b06b4b3923afb1e",L="https://pixabay.com/api/",E=15;async function u(e,t=1){return(await g.get(`${L}`,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:E}})).data}const P=new h(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,close:!0,showCounter:!0,enableKeyboard:!0});function f(e){const t=document.querySelector(".gallery"),s=e.map(n=>`
        <a href="${n.largeImageURL}" class="gallery-item">
            <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
            <div class="info">
                <p class="info-item"><b>Likes</b>: ${n.likes}</p>
                <p class="info-item"><b>Views</b>: ${n.views}</p>
                <p class="info-item"><b>Comments</b>: ${n.comments}</p>
                <p class="info-item"><b>Downloads</b>: ${n.downloads}</p>
            </div>
        </a>
    `).join("");t.insertAdjacentHTML("beforeend",s),P.refresh()}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function c(e){b.error({title:"Error",message:e})}function y(){document.querySelector(".loader-wrapper").style.display="flex"}function m(){document.querySelector(".loader-wrapper").style.display="none"}function I(){document.getElementById("load-more").style.display="block"}function p(){document.getElementById("load-more").style.display="none"}function q(e){window.scrollBy({top:e,behavior:"smooth"})}let i="",a=1,d=0;document.getElementById("search-form").addEventListener("submit",async e=>{if(e.preventDefault(),i=document.getElementById("search-input").value.trim(),i===""){iziToast.warning({title:"Warning",message:"Please enter a search query"});return}a=1,v(),p(),y();try{const t=await u(i,a);d=t.totalHits,t.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(f(t.hits),t.hits.length<d&&I())}catch{c("An error occurred while fetching images. Please try again later.")}finally{m()}});document.getElementById("load-more").addEventListener("click",async()=>{a+=1,y();try{const e=await u(i,a);f(e.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();q(t*2),a*15>=d&&(p(),iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{c("An error occurred while fetching images. Please try again later.")}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
